### ISSUE TITLE
Windows package is missing liblz4.lib

### ISSUE THREAD

**Issue by wesm** [conda-forge/lz4-c-feedstock#1]
This is required for linking dynamically to liblz4.dll. cc @maxris

**Comment by rmax** [comment]
I believe this would fix this issue: https://github.com/conda-forge/lz4-c-feedstock/pull/2/files#diff-d04c86b6bb20341f5f7c53165501a393L57
However, I don't have enough experience with DDLs or a Windows to test it out.

@wesm Do you know if the fix is OK or if there is any other missing file? (`.pdb`, `.exp`, etc)

**Comment by maxhora** [comment]
@rmax , just .lib and .dll files should be enough

**Comment by rmax** [comment]
@MaxRis Updated windows packages (version `1.7.5-1`) are ready on the conda-forge channel.

Please let me know if it works as expected.

**Comment by maxhora** [comment]
@rmax , confirming that I can link dynamically on Windows, thank you!
